# window.py
#
# Copyright 2024 mirkobrombin
# Copyright 2024 muqtadir
#
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundationat version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import json
import logging
import os
from gettext import gettext as _

from gi.repository import Adw, GLib, Gtk

from bootc_installer.utils.builder import Builder
from bootc_installer.utils.finals import _extract_icon_and_name

from bootc_installer.utils.processor import Processor
from bootc_installer.views.confirm import BootcConfirm
from bootc_installer.views.done import BootcDone
from bootc_installer.views.progress import BootcProgress
from bootc_installer.views.recovery_key import BootcRecoveryKey

try:
    from bootc_installer._version import VERSION as _APP_VERSION
except ImportError:
    _APP_VERSION = "unknown"

logger = logging.getLogger("Installer::Window")


@Gtk.Template(resource_path="/org/bootcinstaller/Installer/gtk/window.ui")
class BootcWindow(Adw.ApplicationWindow):
    __gtype_name__ = "BootcWindow"

    carousel = Gtk.Template.Child()
    carousel_indicator_dots = Gtk.Template.Child()
    btn_back = Gtk.Template.Child()
    btn_next = Gtk.Template.Child()
    btn_exit = Gtk.Template.Child()
    btn_about = Gtk.Template.Child()
    btn_credits = Gtk.Template.Child()
    toasts = Gtk.Template.Child()

    def __init__(self, autoinstall_recipe: str | None = None, **kwargs):
        super().__init__(**kwargs)

        logger.info("bootc Installer version: %s", _APP_VERSION)

        self.__autoinstall_recipe = autoinstall_recipe

        # this starts the builder and generates the widgets
        # to put in the carousel
        self.__builder = Builder(self)

        # system views
        self.__view_confirm = BootcConfirm(self)
        self.__view_progress = BootcProgress(self)
        self.__view_recovery_key = BootcRecoveryKey(self)
        self.__view_done = BootcDone(self)

        self.__install_is_encrypted = False
        self.__install_recovery_key = ""

        # sensitivity-tracking state for the header btn_next
        self.__next_page_widget = None
        self.__next_handlers = []
        # Handler ID for update_finals so we can disconnect it on rebuild.
        self.__update_finals_widget = None
        self.__update_finals_handler = None

        # this builds the UI with the widgets generated by the builder
        self.__build_ui()

        # connect system signals
        self.__connect_signals()

        # some variables to track state
        self.install_mode = 0

        # Autoinstall mode: skip the wizard and start immediately.
        if self.__autoinstall_recipe:
            GLib.idle_add(self._start_autoinstall)
        elif os.environ.get("BOOTC_PREVIEW_SCREEN"):
            GLib.idle_add(self.__apply_preview_screen)

    def __connect_signals(self):
        self.btn_back.connect("clicked", self.back)
        self.btn_next.connect("clicked", self.__on_header_next)
        self.btn_exit.connect("clicked", self.__on_exit_clicked)
        self.btn_about.connect("clicked", self.__on_about_clicked)
        self.btn_credits.connect("clicked", self.__on_credits_clicked)
        self.connect("close-request", self.__on_close_request)
        self.carousel.connect("page-changed", self.__on_page_changed)
        self.__reconnect_update_finals()
        self.__view_confirm.connect("installation-confirmed", self.on_installation_confirmed)
        self.__view_recovery_key.connect("recovery-key-acknowledged", self.__on_recovery_key_acknowledged)

        if os.environ.get("BOOTC_TEST"):
            self.carousel.connect("page-changed", self.__on_page_changed_test)
            GLib.timeout_add(600, self.__test_advance_first_page)

    def __reconnect_update_finals(self):
        """(Re-)connect update_finals to the last visible step's btn_next.

        Called after every carousel rebuild so that the correct step triggers
        finals collection when its Next button is clicked.
        """
        # Disconnect previous handler if any.
        if self.__update_finals_widget is not None and self.__update_finals_handler is not None:
            try:
                self.__update_finals_widget.btn_next.disconnect(self.__update_finals_handler)
            except Exception as e:
                logger.debug("Could not disconnect update_finals handler: %s", e)

        target = self.__last_step_widget
        if target is None and self.__builder.widgets:
            target = self.__builder.widgets[-1]

        if target is not None and hasattr(target, "btn_next"):
            self.__update_finals_handler = target.btn_next.connect("clicked", self.update_finals)
            self.__update_finals_widget = target

    def __test_advance_first_page(self):
        page = self.carousel.get_nth_page(0)
        if hasattr(page, "test_auto_advance"):
            page.test_auto_advance()
        return GLib.SOURCE_REMOVE

    def __on_page_changed_test(self, carousel, index):
        page = carousel.get_nth_page(int(index))
        if hasattr(page, "test_auto_advance"):
            # 700ms: enough for animations + update_finals() to have run
            GLib.timeout_add(700, lambda: page.test_auto_advance() or GLib.SOURCE_REMOVE)

    def rebuild_ui(self, mode=1):
        self.install_mode = mode
        self.__build_ui(True, mode)
        self.__reconnect_update_finals()

    def rebuild_ui_after_image(self):
        """Rebuild non-protected steps so they can react to the image selection."""
        self.__build_ui(True, self.install_mode)
        self.__reconnect_update_finals()

    def _is_offline_install(self) -> bool:
        """Detect if this is an offline install (live ISO with baked image).

        Offline installs have the container image pre-loaded on the ISO media,
        so no network pull is needed during step 6 (bootc install). Detected by:
        1. A local_imgref in the recipe (explicit offline source), OR
        2. Running in live ISO mode and the booted image matches the target image
        """
        recipe = self.recipe if hasattr(self, "recipe") else {}
        if recipe.get("local_imgref"):
            return True
        # Check for live ISO indicators
        in_flatpak = os.path.exists("/.flatpak-info")
        etc = "/run/host/etc" if in_flatpak else "/etc"
        live_flag = os.path.exists(f"{etc}/bootc-installer/live-iso-mode")
        live_initramfs = os.path.exists("/run/initramfs/live")
        ostree_booted = os.path.exists("/run/ostree-booted")
        if live_flag or (not in_flatpak and (ostree_booted or live_initramfs)):
            return True
        return False

    def __step_context(self, current_widget=None):
        context = {
            "offline_install": self._is_offline_install(),
            "has_tpm2": os.path.exists("/dev/tpmrm0"),
            "live_iso": not os.path.exists("/.flatpak-info") and os.path.exists("/run/ostree-booted"),
            "sys_recipe": self.recipe if hasattr(self, "recipe") else {},
            "leaf_count": getattr(self, "_image_leaf_count", 2),
            "disk_count": getattr(self, "_installable_disk_count", 2),
        }

        finals = []
        for widget in self.__builder.widgets:
            if widget is current_widget:
                break
            try:
                finals.append(widget.get_finals())
            except Exception as exc:
                logger.debug("(%s) Failed to collect step context finals: %s", getattr(widget, "__gtype_name__", type(widget).__name__), exc)
        context["finals"] = finals
        return context

    def __build_ui(self, rebuild=False, mode=0):
        property_list = self.__builder.property_list
        context = self.__step_context()

        if rebuild:
            self.carousel.remove(self.__view_confirm)
            self.carousel.remove(self.__view_progress)
            self.carousel.remove(self.__view_recovery_key)
            self.carousel.remove(self.__view_done)

        self.__last_step_widget = None

        if "VANILLA_FORCE_TOUR" not in os.environ:
            for i, widget in enumerate(self.__builder.widgets):
                if rebuild:
                    if "protected" in property_list[i]:
                        continue
                    else:
                        try:
                            self.carousel.remove(widget)
                        except Exception as e:
                            logger.debug("(%s) carousel.remove skipped (not present): %s", getattr(widget, "__gtype_name__", type(widget).__name__), e)
                if "custom_image" in property_list[i] and mode == 0:
                    continue
                if "default_image" in property_list[i] and mode == 1:
                    continue
                if getattr(widget, "skip_screen", False):
                    logger.info("(%s) Skipping screen (skip_screen=True)", getattr(widget, "__gtype_name__", type(widget).__name__))
                    continue
                if hasattr(widget, "should_show") and not widget.should_show(context):
                    logger.info("(%s) Skipping screen (should_show=False)", getattr(widget, "__gtype_name__", type(widget).__name__))
                    continue
                logger.info("(%s) Adding widget to carousel", getattr(widget, "__gtype_name__", type(widget).__name__))
                self.carousel.append(widget)
                self.__last_step_widget = widget
        else:
            self.__on_page_changed()

        self.carousel.append(self.__view_confirm)
        self.carousel.append(self.__view_progress)
        self.carousel.append(self.__view_recovery_key)
        self.carousel.append(self.__view_done)

    def __on_page_changed(self, *args):
        cur_index = self.carousel.get_position()
        page = self.carousel.get_nth_page(cur_index)

        logger.info("(%s) Page is changing...", getattr(page, "__gtype_name__", type(page).__name__))

        # Disconnect sensitivity tracking from previous page
        if self.__next_page_widget is not None:
            for h in self.__next_handlers:
                try:
                    self.__next_page_widget.btn_next.disconnect(h)
                except Exception as e:
                    logger.debug("Could not disconnect next button handler: %s", e)
            self.__next_page_widget = None
            self.__next_handlers = []

        is_final = page in [self.__view_progress, self.__view_recovery_key, self.__view_done]
        is_confirm = page == self.__view_confirm

        if is_confirm:
            logger.info("(%s) It is the confirm page", getattr(page, "__gtype_name__", type(page).__name__))
            self.btn_back.set_visible(True)
            self.btn_back.set_sensitive(True)
            self.carousel_indicator_dots.set_visible(False)
            self.btn_next.set_visible(False)
            return

        if is_final:
            logger.info("(%s) It is a final page", getattr(page, "__gtype_name__", type(page).__name__))
            self.btn_back.set_visible(False)
            self.btn_back.set_sensitive(False)
            self.carousel_indicator_dots.set_visible(False)
            self.btn_next.set_visible(False)
            return

        logger.info("(%s) It is not a final page", getattr(page, "__gtype_name__", type(page).__name__))
        self.btn_back.set_visible(cur_index != 0.0)
        self.btn_back.set_sensitive(cur_index != 0.0)
        self.carousel_indicator_dots.set_visible(cur_index != 0.0)

        if hasattr(page, "on_shown"):
            try:
                page.on_shown(self.__step_context(page))
            except Exception as exc:
                logger.warning("(%s) on_shown failed: %s", getattr(page, "__gtype_name__", type(page).__name__), exc)

        # Sync header btn_next with the current page's btn_next sensitivity only.
        # Visibility of the per-page btn_next is always false (hidden in favour of
        # the header button), so we must NOT mirror it — the header btn_next should
        # always be visible on step pages; only its sensitivity tracks the page.
        if hasattr(page, "btn_next"):
            self.btn_next.set_visible(True)
            self.btn_next.set_sensitive(page.btn_next.get_sensitive())

            def _sync(widget, _param):
                self.btn_next.set_sensitive(widget.get_sensitive())

            self.__next_handlers = [
                page.btn_next.connect("notify::sensitive", _sync),
            ]
            self.__next_page_widget = page
        else:
            self.btn_next.set_visible(False)

    def __on_header_next(self, *args):
        cur_index = int(self.carousel.get_position())
        page = self.carousel.get_nth_page(cur_index)
        if hasattr(page, "btn_next"):
            page.btn_next.emit("clicked")

    def __on_close_request(self, *args):
        if self.__is_done():
            self.get_application().quit()
            return True
        self.__on_exit_clicked()
        return True  # block the default close; dialog will quit() if confirmed

    def __is_done(self):
        cur_index = int(self.carousel.get_position())
        return self.carousel.get_nth_page(cur_index) is self.__view_done

    def __find_page_index(self, target_page):
        for index in range(self.carousel.get_n_pages()):
            if self.carousel.get_nth_page(index) is target_page:
                return index
        return -1

    def __go_to_page(self, target_page, animate=True):
        if target_page is None:
            return
        index = self.__find_page_index(target_page)
        if index < 0:
            return
        page = self.carousel.get_nth_page(index)
        if page is not None:
            self.carousel.scroll_to(page, animate)

    @staticmethod
    def __normalize_screen_name(name: str) -> str:
        return name.strip().lower().replace("_", "-")

    def __find_preview_target(self, screen_name: str):
        normalized = self.__normalize_screen_name(screen_name)
        static_pages = {
            "confirm": self.__view_confirm,
            "progress": self.__view_progress,
            "recovery-key": self.__view_recovery_key,
            "done": self.__view_done,
        }
        if normalized in static_pages:
            return static_pages[normalized]

        for widget in self.__builder.widgets:
            candidates = {
                getattr(widget, "_bootc_step_key", ""),
                getattr(widget, "_bootc_template", ""),
                getattr(widget, "__gtype_name__", type(widget).__name__),
            }
            normalized_candidates = {
                self.__normalize_screen_name(candidate)
                for candidate in candidates
                if candidate
            }
            if normalized in normalized_candidates:
                return widget
        return None

    def __apply_preview_screen(self):
        screen_name = os.environ.get("BOOTC_PREVIEW_SCREEN", "").strip()
        if not screen_name:
            return False

        target = self.__find_preview_target(screen_name)
        if target is None:
            logger.warning("Unknown BOOTC_PREVIEW_SCREEN=%s", screen_name)
            return False

        if target is self.__view_confirm:
            self.update_finals()
        elif target is self.__view_recovery_key:
            self.__view_recovery_key.set_recovery_key("demo-preview-recovery-key")
        elif target is self.__view_done:
            self.update_finals()
            self.__view_done.set_result(True, None)

        self.__go_to_page(target, animate=False)

        if target is self.__view_progress:
            if os.environ.get("BOOTC_DEMO"):
                self.__view_progress.start_demo()
            else:
                # Even without a demo install, configure the video so it plays
                self.__view_progress.configure_video_preview()

        return False

    def __finals_use_encryption(self):
        for final in getattr(self, "finals", []):
            encryption = final.get("encryption") if isinstance(final, dict) else None
            if not isinstance(encryption, dict):
                continue
            enc_type = encryption.get("type", "")
            if encryption.get("use_encryption") or enc_type not in ("", "none"):
                return True
        return False

    def __recipe_uses_encryption(self, recipe_path: str) -> bool:
        try:
            with open(recipe_path) as recipe_file:
                recipe = json.load(recipe_file)
        except (OSError, json.JSONDecodeError) as exc:
            logger.warning("Failed to inspect install recipe %s: %s", recipe_path, exc)
            return False

        encryption = recipe.get("encryption", {})
        if not isinstance(encryption, dict):
            return False
        return encryption.get("type", "none") != "none"

    def __on_recovery_key_acknowledged(self, *args):
        self.__go_to_page(self.__view_done)

    def __on_about_clicked(self, *args):
        # Vendor and website come from the branding contract (branding.json,
        # then os-release); nothing here names a product.
        b = self.recipe.get("branding", {}) if hasattr(self, "recipe") else {}
        kwargs = dict(
            application_name=_("bootc Installer"),
            version=_APP_VERSION,
            license_type=Gtk.License.GPL_3_0,
        )
        if b.get("home_url"):
            kwargs["website"] = b["home_url"]
        if b.get("vendor"):
            kwargs["developer_name"] = b["vendor"]
        dialog = Adw.AboutDialog(**kwargs)
        dialog.present(self)

    def __on_credits_clicked(self, *args):
        from bootc_installer.windows.dialog_credits import BootcCreditsWindow
        BootcCreditsWindow(self).show()

    def __on_exit_clicked(self, *args):
        if self.__is_done():
            self.get_application().quit()
            return
        dialog = Adw.AlertDialog(
            heading=_("Exit Installer?"),
            body=_("Any progress will be lost."),
        )
        dialog.add_response("cancel", _("Cancel"))
        dialog.add_response("exit", _("Exit"))
        dialog.set_response_appearance("exit", Adw.ResponseAppearance.DESTRUCTIVE)
        dialog.set_default_response("cancel")
        dialog.set_close_response("cancel")
        dialog.connect("response", self.__on_exit_response)
        dialog.present(self)

    def __on_exit_response(self, dialog, response):
        if response == "exit":
            # Terminate fisherman if it's still running to avoid orphaned
            # root processes and partially-written disk state.
            self.__view_progress.terminate()
            self.get_application().quit()

    def update_finals(self, *args):
        # collect all the finals
        if "VANILLA_FORCE_TOUR" not in os.environ:
            self.finals = self.__builder.get_finals()
        else:
            self.finals = json.loads(os.environ["VANILLA_FORCE_TOUR"])

        self.pretty_name, self.selected_icon = _extract_icon_and_name(self.finals)

        self.__view_confirm.update(self.finals)

    def on_installation_confirmed(self, *args):
        self.__install_is_encrypted = self.__finals_use_encryption()
        self.__install_recovery_key = ""

        # Apply any hostname edit the user made on the confirm screen.
        hostname_override = self.__view_confirm.get_hostname_override()
        if hostname_override:
            for final in self.finals:
                if isinstance(final, dict) and "hostname" in final:
                    final["hostname"] = hostname_override
                    break

        if os.environ.get("BOOTC_DEMO"):
            self.next()
            self.__view_progress.start_demo()
            return

        recipe = Processor.gen_install_recipe(
            self.recipe.get("log_file", "/tmp/vanilla_installer.log"),
            self.finals,
            self.recipe,
        )
        self.next()
        self.__view_progress.start(recipe)

    def _start_autoinstall(self):
        """Called via GLib.idle_add when --autoinstall was passed.

        Navigates directly to the progress view and starts fisherman with the
        pre-built recipe file, bypassing the entire wizard.
        """
        logger.info(f"Autoinstall: starting with recipe {self.__autoinstall_recipe}")
        self.__install_is_encrypted = self.__recipe_uses_encryption(self.__autoinstall_recipe)
        self.__install_recovery_key = ""

        progress_index = self.__find_page_index(self.__view_progress)
        if progress_index >= 0:
            page = self.carousel.get_nth_page(progress_index)
            self.carousel.scroll_to(page, False)
        self.__view_progress.start(self.__autoinstall_recipe)
        return False  # remove idle callback

    def next(self, widget=None, fn=None, *args):
        logger.info("Going to next page")

        cur_index = self.carousel.get_position()
        if int(cur_index) >= self.carousel.get_n_pages() - 1:
            logger.info(f"Already on last page ({int(cur_index)}), ignoring next()")
            return
        page = self.carousel.get_nth_page(cur_index)
        if getattr(page, "delta", False):
            logger.info(f"Removing deltas of page {int(cur_index)}")
            page.del_deltas()
        logger.info(f"Next page is {int(cur_index + 1)}")

        if fn is not None:
            logger.info("Executing page's custom function")
            fn()
            logger.info("Finished executing page's custom function")

        page = self.carousel.get_nth_page(cur_index + 1)
        self.carousel.scroll_to(page, True)
        if getattr(page, "delta", False):
            logger.info(f"Generating deltas of page {int(cur_index + 1)}")
            page.gen_deltas()

    def back(self, *args):
        logger.info("Going to previous page")

        cur_index = self.carousel.get_position()
        page = self.carousel.get_nth_page(cur_index)
        if getattr(page, "delta", False):
            page.del_deltas()
        logger.info(f"Previous page is {int(cur_index - 1)}")

        page = self.carousel.get_nth_page(cur_index - 1)
        self.carousel.scroll_to(page, True)
        if getattr(page, "delta", False):
            page.gen_deltas()

    def toast(self, message, timeout=3):
        toast = Adw.Toast.new(message)
        toast.props.timeout = timeout
        self.toasts.add_toast(toast)

    def set_installation_result(self, result, terminal, boot_id="", recovery_key="", elapsed_secs=0):
        if result:
            logger.info("Installation complete!")
        else:
            logger.error("Installation failed!")

        self.__install_recovery_key = recovery_key or self.__install_recovery_key

        # Pass installed image ref to done screen so it can schedule a registry warmup.
        image_ref = None
        for f in getattr(self, "finals", []):
            if isinstance(f, dict):
                image_ref = f.get("custom_image") or f.get("selected_image")
                if image_ref:
                    break

        self.__view_done.set_result(result, terminal, boot_id, elapsed_secs,
                                    image_ref=image_ref)

        if result and self.__install_is_encrypted and self.__install_recovery_key:
            # Only show the recovery key screen when fisherman actually emitted a
            # random recovery key (tpm2-luks only). luks-passphrase and
            # tpm2-luks-passphrase use the user's own passphrase — no random key
            # is generated, so there is nothing to display here.
            self.__view_recovery_key.set_recovery_key(self.__install_recovery_key)
            self.__go_to_page(self.__view_recovery_key)
            return

        self.__go_to_page(self.__view_done)
