"""Test that generated fisherman recipes conform to schema."""

import json
import tempfile
from pathlib import Path
import sys
import pytest

# Add parent dir to path so we can import validate_recipe
sys.path.insert(0, str(Path(__file__).parent))
from validate_recipe import validate_recipe


def test_generated_recipe_validates():
    """Test that a recipe generated by Processor passes schema validation."""
    # Import here to avoid issues in test discovery
    from bootc_installer.utils.processor import Processor
    
    # Create mock finals data that Processor.gen_install_recipe expects
    finals = [
        {
            "disk": {
                "auto": {
                    "disk": "/dev/vda",
                    "layout": "gpt",
                }
            },
            "encryption": {
                "type": "none",
                "passphrase": "",
            },
            "hostname": "test-system",
        },
        {
            "selected_image": "ghcr.io/bootcrew/fedora-silverblue:latest",
        },
        {
            "user": {
                "username": "testuser",
                "fullname": "Test User",
                "password": "testpass123",
                "groups": ["wheel"],
            },
        },
        {
            "flatpaks": [],
        },
    ]
    
    sys_recipe = {
        "imgref": "ghcr.io/bootcrew/fedora-silverblue:latest",
    }
    
    # Generate recipe
    with tempfile.TemporaryDirectory() as tmpdir:
        recipe_path = Processor.gen_install_recipe(
            log_path=str(Path(tmpdir) / "install.log"),
            finals=finals,
            sys_recipe=sys_recipe,
        )
        
        # Validate it
        assert validate_recipe(recipe_path), \
            f"Generated recipe at {recipe_path} does not conform to schema"
        
        # Also verify we can load and inspect it
        with open(recipe_path) as f:
            recipe = json.load(f)
        
        # Check that required fields are present
        assert recipe.get("disk") == "/dev/vda"
        assert recipe.get("hostname") == "test-system"
        assert recipe.get("image") == "ghcr.io/bootcrew/fedora-silverblue:latest"
        assert recipe.get("user", {}).get("username") == "testuser"


if __name__ == "__main__":
    test_generated_recipe_validates()
    print("✓ Test passed")
