#!/usr/bin/env python3
"""Write copy-defaults.json into frontends/niri/ui/installer.qml.

Niri's QML needs the defaults as a JS object literal: it cannot read a file,
and the backend that would send them is stubbed during every capture run.
That makes the table a copy, and copies drift -- this one was missing
`welcome_install_subtitle` from the day the key was added.

So the table is generated, never hand-edited, and
tests/unit/test_copy_coverage.py parses it back out and requires it to match
the canonical file key for key and value for value. Run this after editing
shared/branding/copy-defaults.json, alongside the other copies.
"""

import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
CANONICAL = REPO / "shared" / "branding" / "copy-defaults.json"
QML = REPO / "frontends" / "niri" / "ui" / "installer.qml"

BEGIN = "        // COPY-DEFAULTS-BEGIN (generated by shared/branding/generate-qml-defaults.py)\n"
END = "        // COPY-DEFAULTS-END\n"


def render(defaults):
    lines = [BEGIN, "        const defaults = ({\n"]
    for i, (key, value) in enumerate(defaults.items()):
        comma = "," if i < len(defaults) - 1 else ""
        lines.append(f"            {key}: {json.dumps(value, ensure_ascii=False)}{comma}\n")
    lines.append("        })\n")
    lines.append(END)
    return "".join(lines)


def main():
    raw = json.loads(CANONICAL.read_text())
    defaults = {k: v for k, v in raw.items() if not k.startswith("_")}

    text = QML.read_text()
    if BEGIN not in text or END not in text:
        print(f"{QML} has no COPY-DEFAULTS markers", file=sys.stderr)
        return 1
    head, rest = text.split(BEGIN, 1)
    _old, tail = rest.split(END, 1)
    QML.write_text(head + render(defaults) + tail)
    print(f"wrote {len(defaults)} keys into {QML.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
