#!/usr/bin/env python3
"""Fold every frontend's capture into one walkthrough + parity document.

Input:  a directory holding one sub-directory per frontend flavor (gnome, kde,
        cosmic, niri, xfce), each with the `NN-<page>.png` frames,
        `walkthrough.gif`, `walkthrough-<flavor>.json` and optionally
        `captions.json` that the frontend's capture harness produced.
Output: <outdir>/README.md, <outdir>/summary.json and a copy of every
        frame under <outdir>/<flavor>/.

    python3 shared/walkthrough/aggregate.py <captures-dir> docs/walkthrough

The parity matrix is computed from the reports' `screens` maps, which every
frontend's harness fills against the SAME contract
(shared/walkthrough/parity_report.py: SCREENS). A frontend with no report
reads as "pending"; a report whose `screens` values are null (PNG-only
capture) reads as "not measured". Neither is a pass.

`--strict` exits 1 when a frontend that HAS a text-bearing report misses a
required screen. The CI job runs without it and annotates instead: the point
of this page is to make drift visible, and a gate that fails the docs build
would just get the emitter disabled.
"""

import argparse
import json
import os
import re
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import parity_report

FLAVORS = [
    ("gnome", "GNOME", "GTK4 / libadwaita (Python)", "bootc_installer/"),
    ("kde", "KDE Plasma", "Qt 6 / Kirigami (C++ + QML)", "frontends/kde/"),
    ("cosmic", "COSMIC", "libcosmic / iced (Rust)", "frontends/cosmic/"),
    ("niri", "Niri", "Quickshell QML + Go backend", "frontends/niri/"),
    ("xfce", "XFCE", "GTK3 / PyGObject", "frontends/xfce/"),
]

PENDING, UNMEASURED, YES, NO = "pending", "not measured", "yes", "no"


def load_flavor(root, flavor):
    d = os.path.join(root, flavor)
    if not os.path.isdir(d):
        return None
    frames = sorted(f for f in os.listdir(d) if re.match(r"^\d\d-.*\.png$", f))
    report = None
    rp = os.path.join(d, f"walkthrough-{flavor}.json")
    if os.path.exists(rp):
        with open(rp) as fh:
            report = json.load(fh)
    captions = {}
    cp = os.path.join(d, "captions.json")
    if os.path.exists(cp):
        with open(cp) as fh:
            captions = json.load(fh)
    return {"dir": d, "frames": frames, "report": report, "captions": captions,
            "gif": ("walkthrough.gif"
                    if os.path.exists(os.path.join(d, "walkthrough.gif")) else None)}


def cell(data, screen_id):
    if data is None or data["report"] is None:
        return PENDING
    val = (data["report"].get("screens") or {}).get(screen_id)
    if val is None:
        return UNMEASURED
    return YES if val else NO


def render_cell(state, required):
    if state == YES:
        return "✅"
    if state == NO:
        return "❌" if required else "⚠️"
    if state == UNMEASURED:
        return "➖"
    return "⏳"


def page_label(frame):
    return re.sub(r"^\d\d-", "", frame[:-4]).replace("_", " ").replace("-", " ")


def build(root, outdir, repo, strict):
    os.makedirs(outdir, exist_ok=True)
    data = {flavor: load_flavor(root, flavor) for flavor, *_ in FLAVORS}

    # Copy frames so the document is self-contained and diffable in git.
    for flavor, d in data.items():
        dest = os.path.join(outdir, flavor)
        if d is None:
            continue
        if os.path.isdir(dest):
            shutil.rmtree(dest)
        os.makedirs(dest)
        for f in d["frames"] + ([d["gif"]] if d["gif"] else []):
            shutil.copy2(os.path.join(d["dir"], f), os.path.join(dest, f))
        if d["report"] is not None:
            with open(os.path.join(dest, f"walkthrough-{flavor}.json"), "w") as fh:
                json.dump(d["report"], fh, indent=2)
                fh.write("\n")

    lines = []
    w = lines.append
    w("# Installer frontends: walkthrough and parity")
    w("")
    w("Generated by `shared/walkthrough/aggregate.py` from each frontend's own")
    w("screenshot job. Every frame is rendered in CI from the real UI, never")
    w("hand-taken, so this page cannot drift from the apps. Do not edit by hand.")
    w("")
    w("## Parity matrix")
    w("")
    w("Which screens of the shared contract each frontend reaches, as measured by")
    w("reading the visible widget text of every captured page against")
    w("`shared/walkthrough/parity_report.py`. ✅ reached · ❌ required screen not")
    w("reached · ⚠️ optional screen not reached · ➖ not measured (this frontend's")
    w("harness does not read its widget text yet) · ⏳ no capture on record.")
    w("")
    header = "| Screen | " + " | ".join(name for _, name, *_ in FLAVORS) + " |"
    w(header)
    w("|---|" + "---|" * len(FLAVORS))
    problems = []
    for sc in parity_report.SCREENS:
        row = [f"`{sc['id']}` {'(required)' if sc['required'] else ''}".strip()]
        for flavor, name, *_ in FLAVORS:
            st = cell(data[flavor], sc["id"])
            row.append(render_cell(st, sc["required"]))
            if st == NO and sc["required"]:
                problems.append(f"{name}: required screen '{sc['id']}' not reached")
        w("| " + " | ".join(row) + " |")
    w("")
    w("| Frontend | Pages | Rendered | Transitions | Harness |")
    w("|---|---|---|---|---|")
    for flavor, name, _toolkit, _path in FLAVORS:
        d = data[flavor]
        if d is None or d["report"] is None:
            w(f"| {name} | {len(d['frames']) if d else 0} | – | – | pending |")
            continue
        r = d["report"]
        # No run id or link here on purpose: this file is committed, and a
        # value that changes on every CI run turns each re-run into a new
        # commit even when nothing rendered differently (dev grew two
        # identical-looking walkthrough commits in five minutes on the
        # first day). The run ids stay in the job log.
        w(f"| {name} | {r.get('frames')} | {r.get('rendered_frames')} | "
          f"{r.get('advanced_transitions')} | {r.get('harness', '')} |")
    w("")
    if problems:
        w("**Gaps:**")
        w("")
        for p in problems:
            w(f"- {p}")
        w("")

    for flavor, name, toolkit, path in FLAVORS:
        d = data[flavor]
        w(f"## {name}")
        w("")
        w(f"{toolkit}. Source: `{path}`.")
        w("")
        if d is None or not d["frames"]:
            w("_No capture on record yet._")
            w("")
            continue
        if d["gif"]:
            w(f'<p align="center"><img src="{flavor}/walkthrough.gif" '
              f'alt="{name} installer walkthrough" width="640"></p>')
            w("")
        w("| | |")
        w("|---|---|")
        pages = {p["name"]: p for p in (d["report"] or {}).get("pages", [])}
        for f in d["frames"]:
            label = page_label(f)
            caption = d["captions"].get(f) or ""
            key = re.sub(r"^\d\d-", "", f[:-4])
            p = pages.get(key) or pages.get(f[:-4]) or {}
            rendered = p.get("rendered")
            flag = "" if rendered in (True, None) else " **(did not render)**"
            excerpt = (p.get("text_excerpt") or "").strip()
            excerpt = f" <br><sub>{excerpt[:140]}</sub>" if excerpt else ""
            w(f'| <img src="{flavor}/{f}" width="360"> | **{label}**{flag} {caption}{excerpt} |')
        w("")

    with open(os.path.join(outdir, "README.md"), "w") as fh:
        fh.write("\n".join(lines) + "\n")

    summary = {
        "screens": {sc["id"]: {flavor: cell(data[flavor], sc["id"]) for flavor, *_ in FLAVORS}
                    for sc in parity_report.SCREENS},
        "frontends": {flavor: {
            "frames": len(d["frames"]) if d else 0,
            "report": bool(d and d["report"]),
        } for flavor, *_ in FLAVORS},
        "problems": problems,
    }
    with open(os.path.join(outdir, "summary.json"), "w") as fh:
        json.dump(summary, fh, indent=2)
        fh.write("\n")

    for p in problems:
        print(f"::warning::{p}")
    print(f"wrote {os.path.join(outdir, 'README.md')} ({len(problems)} gap(s))")
    return 1 if (strict and problems) else 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("captures")
    ap.add_argument("outdir")
    ap.add_argument("--repo", default="")
    ap.add_argument("--strict", action="store_true")
    args = ap.parse_args()
    return build(args.captures, args.outdir, args.repo, args.strict)


if __name__ == "__main__":
    sys.exit(main())
